services:
    glavweb_uploader_dropzone.form.image_type:
        class: Glavweb\UploaderDropzoneBundle\Form\ImageType
        arguments: ["%glavweb_uploader_dropzone.config%", "@router", "@doctrine", "@glavweb_uploader.uploader_manager", "@glavweb_uploader.util.media_structure"]
        tags:
            - { name: form.type, alias: Glavweb\UploaderDropzoneBundle\Form\ImageType }

    glavweb_uploader_dropzone.form.image_collection_type:
        class: Glavweb\UploaderDropzoneBundle\Form\ImageCollectionType
        arguments: ["%glavweb_uploader_dropzone.config%", "@router", "@doctrine", "@glavweb_uploader.uploader_manager", "@glavweb_uploader.util.media_structure"]
        tags:
            - { name: form.type, alias: Glavweb\UploaderDropzoneBundle\Form\ImageCollectionType }

    glavweb_uploader_dropzone.form.video_type:
        class: Glavweb\UploaderDropzoneBundle\Form\VideoType
        arguments: ["%glavweb_uploader_dropzone.config%", "@router", "@doctrine", "@glavweb_uploader.uploader_manager", "@glavweb_uploader.util.media_structure"]
        tags:
            - { name: form.type, alias: Glavweb\UploaderDropzoneBundle\Form\VideoType }

    glavweb_uploader_dropzone.form.video_collection_type:
        class: Glavweb\UploaderDropzoneBundle\Form\VideoCollectionType
        arguments: ["%glavweb_uploader_dropzone.config%", "@router", "@doctrine", "@glavweb_uploader.uploader_manager", "@glavweb_uploader.util.media_structure"]
        tags:
            - { name: form.type, alias: Glavweb\UploaderDropzoneBundle\Form\VideoCollectionType }

    glavweb_uploader_dropzone.form.file_type:
        class: Glavweb\UploaderDropzoneBundle\Form\FileType
        arguments: ["%glavweb_uploader_dropzone.config%", "@router", "@doctrine", "@glavweb_uploader.uploader_manager", "@glavweb_uploader.util.media_structure"]
        tags:
            - { name: form.type, alias: Glavweb\UploaderDropzoneBundle\Form\FileType }
